### ISSUE TITLE
 Price lookup fails for delisted securities

### ISSUE THREAD

**Issue by pa-wills** [pa-wills/ComputeTSR#7]
(u'2007-03-16', u'Buy', u'PBL.AX', 700, 19, 29.95, 13329.95, u'', u'2007-12-03', u'Sell', 20.8, 0, 14560, u'This was the close price on Nov 30, the final day of trading - see my Quicken extracts')
Today is: 2020-03-07
Days held: 4740
Traceback (most recent call last):
  File "calcTsr.py", line 228, in <module>
    main()
  File "calcTsr.py", line 101, in main
    closePrice = (cursor.fetchall())[0][0]

**Comment by pa-wills** [comment]
So, anything that has been de-listed will have been also SOLD. That's an invariant. So - I need to make this conditional, or use an exception, or do something to make this safer.

I then need to make a test case.

**Comment by pa-wills** [comment]
fixed in dev just now
